-- 멤버별 주문 리스트  결과:2번회원 주문번호 1,5
SELECT ORDER_NO, PACKAGE_NAME, PACKAGE_IMG,
      ORDER_DATE, DELIVERY_CODE, ORDER_ADDRESS,ORDER_NAME,ORDER_TEL
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
JOIN "PACKAGE" USING (PACKAGE_NO)
LEFT JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "DELIVERY" USING (ORDER_NO)
LEFT JOIN "MENU" USING(MENU_NO)
WHERE MEMBER_NO =2
GROUP BY ORDER_NO,PACKAGE_NAME,PACKAGE_IMG,
       ORDER_DATE, DELIVERY_CODE,
       ORDER_ADDRESS,ORDER_NAME,ORDER_TEL
ORDER BY ORDER_NO DESC;

-- 주문별 메뉴   결과:2번회원 주문번호1에 대한 메뉴
SELECT DISTINCT ORDER_MENU_NO, MENU_NO, MENU_NAME, MENU_PRICE, MENU_IMG 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_NO=1
AND MENU_DEL_FL='N'
ORDER BY ORDER_MENU_NO;


--메뉴별 옵션  결과:2번회원 주문번호1에 대한 옵션
SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=1
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;


SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=2
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;


SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=3
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;



-- 선택한 패키지별 가격
SELECT DISTINCT CART_NO, PACKAGE_NO, PACKAGE_NAME, PACKAGE_TYPE, PACKAGE_IMG,
	(SELECT SUM(MENU_PRICE) + SUM(NVL(TOTAL_OPT_PRICE,0)) TOTAL FROM (
   SELECT  M.MENU_PRICE,
      (SELECT SUM(NVL(OPTION_PRICE,0) * NVL(CART_OPTION_COUNT,0))  
      FROM CART_MENU_OPTION CMO
      JOIN "OPTION" O ON(CMO.OPTION_NO = O.OPTION_NO)
      WHERE CMO.CART_MENU_NO = CM.CART_MENU_NO) TOTAL_OPT_PRICE
   FROM CART C
   JOIN CART_MENU CM ON (C.CART_NO = CM.CART_NO)
   JOIN MENU M ON (CM.MENU_NO = M.MENU_NO)
   WHERE C.MEMBER_NO = 4
)) TOTAL
FROM CART
LEFT JOIN CART_MENU USING (CART_NO)
LEFT JOIN CART_MENU_OPTION USING (CART_MENU_NO)
JOIN "PACKAGE" USING (PACKAGE_NO)
LEFT JOIN "OPTION" USING (OPTION_NO)
WHERE MEMBER_NO = 4