-- 멤버별 주문 리스트  결과:2번회원 주문번호 1,5
SELECT ORDER_NO, PACKAGE_NAME, PACKAGE_IMG,
      ORDER_DATE, DELIVERY_CODE, ORDER_ADDRESS,ORDER_NAME,ORDER_TEL
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
JOIN "PACKAGE" USING (PACKAGE_NO)
LEFT JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "DELIVERY" USING (ORDER_NO)
LEFT JOIN "MENU" USING(MENU_NO)
WHERE MEMBER_NO =2
GROUP BY ORDER_NO,PACKAGE_NAME,PACKAGE_IMG,
       ORDER_DATE, DELIVERY_CODE,
       ORDER_ADDRESS,ORDER_NAME,ORDER_TEL
ORDER BY ORDER_NO DESC;

-- 주문별 메뉴   결과:2번회원 주문번호1에 대한 메뉴
SELECT DISTINCT ORDER_MENU_NO, MENU_NO, MENU_NAME, MENU_PRICE, MENU_IMG 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_NO=1
AND MENU_DEL_FL='N'
ORDER BY ORDER_MENU_NO;


--메뉴별 옵션  결과:2번회원 주문번호1에 대한 옵션
SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=1
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;


SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=2
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;


SELECT OPTION_NO, OPTION_NAME, OPTION_COUNT, OPTION_PRICE 
FROM "ORDER"
LEFT JOIN ORDER_MENU USING (ORDER_NO)
LEFT JOIN ORDER_MENU_OPTION USING (ORDER_MENU_NO)
LEFT JOIN "PACKAGE" USING (PACKAGE_NO)
JOIN "OPTION" USING (OPTION_NO)
LEFT JOIN "MENU" USING (MENU_NO)
WHERE ORDER_MENU_NO=3
AND MENU_DEL_FL='N'
ORDER BY OPTION_NO;