-- 판매 수량 함수 (offset, 메뉴번호)
CREATE OR REPLACE FUNCTION ORDER_COUNT(VAL NUMBER, MAIN_NO NUMBER)
   RETURN NUMBER 
IS 
   RES_VAL NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO RES_VAL
   FROM "ORDER_MENU" SUB
   JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
   WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
               WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM') + VAL)
   AND SUB.MENU_NO = MAIN_NO;
   RETURN RES_VAL;
END;



-- 메뉴 금액 합 함수 (offset, 메뉴번호)
CREATE OR REPLACE FUNCTION TOTAL_MENU_PRICE(VAL NUMBER, MAIN_NO NUMBER)
   RETURN NUMBER 
IS 
   RES_VAL NUMBER;
BEGIN
   SELECT NVL(SUM(MENU_PRICE),0)
   INTO RES_VAL
   FROM "ORDER_MENU" SUB
   JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
   WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
               WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM') + VAL)
   AND SUB.MENU_NO = MAIN_NO;
   RETURN RES_VAL;
END;
/


-- 서브쿼리버전
SELECT MENU_NO,
   ORDER_COUNT(-1, MAIN.MENU_NO) "전월판매수량",
   TOTAL_MENU_PRICE(-1, MAIN.MENU_NO) "전월매출",
   ORDER_COUNT(0, MAIN.MENU_NO) "당월판매수량",
   TOTAL_MENU_PRICE(0, MAIN.MENU_NO) "당월"
FROM MENU MAIN
ORDER BY 1;



SELECT MENU_NO,
   (SELECT COUNT(*)
      FROM "ORDER_MENU" SUB
      JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
      WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
                  WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM') -1)
      AND SUB.MENU_NO = MAIN.MENU_NO) "전월판매수량",
   (SELECT NVL(SUM(MENU_PRICE),0)
      FROM "ORDER_MENU" SUB
      JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
      WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
                  WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM') -1)
      AND SUB.MENU_NO = MAIN.MENU_NO) "전월",
   (SELECT COUNT(*)
      FROM "ORDER_MENU" SUB
      JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
      WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
                  WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM'))
      AND SUB.MENU_NO = MAIN.MENU_NO) "당월판매수량",
   (SELECT NVL(SUM(MENU_PRICE),0)
      FROM "ORDER_MENU" SUB
      JOIN "MENU" M ON (SUB.MENU_NO = M.MENU_NO)
      WHERE ORDER_NO IN (SELECT ORDER_NO FROM "ORDER"
                  WHERE TO_CHAR(ORDER_DATE,'YYMM') = TO_CHAR(SYSDATE,'YYMM'))
      AND SUB.MENU_NO = MAIN.MENU_NO) "당월"
FROM MENU MAIN;